export const actionTypes ={

SET_MOVIES: "SET_MOVIES",
SET_GENRES: "SET_GENRES",
SET_MOVIES_LOADİNG: "SET_MOVIES_LOADİNG",
SET_GENRES_LOADİNG: "SET_GENRES_LOADİNG",
SET_MOVIES_ERROR: "SET_MOVIES_ERROR",
SET_GENRES_ERROR: "SET_GENRES_ERROR",


};
